; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
default_envs = yolo_uno

[env:yolo_uno]
platform = espressif32
board = yolo_uno
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_compat_mode = strict
lib_deps = 
	robtillaart/DHT20@^0.3.1
	adafruit/Adafruit NeoPixel@^1.15.1
	ESP Async WebServer
	bblanchon/ArduinoJson@^6.21.5
	mobizt/FirebaseClient@^2.2.5
lib_extra_dirs = 
	lib
	lib/Utils
board_build.filesystem = littlefs


[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_compat_mode = strict
lib_deps = 
	robtillaart/DHT20@^0.3.1
	adafruit/Adafruit NeoPixel@^1.15.1
	ESP Async WebServer
	bblanchon/ArduinoJson@^6.21.5
	mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.17
lib_extra_dirs = 
	lib
	lib/Utils
board_build.filesystem = littlefs
board_build.partitions = partitions/ota_2m.csv


